#name of the workflow

name: First Workflow

#When this workflow will get executed, after that we will define event or events when this workflow will get trigger to run
on: workflow_dispatch           #it's an event which wait for the user to manually start to trigger this workflow workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done bye"
